# Generated by Django 3.1.2 on 2020-11-04 22:41

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('location', models.CharField(max_length=100)),
                ('lat', models.CharField(blank=True, max_length=50)),
                ('lon', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BeaconPark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('nearest_city', models.CharField(max_length=200)),
                ('lat', models.CharField(max_length=50)),
                ('lon', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50)),
                ('class_type', models.CharField(choices=[('1', 'AIARE 1'), ('2', 'AIARE 2'), ('3', 'Avalanche Rescue')], max_length=1)),
                ('location', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='Username')),
                ('first_name', models.CharField(max_length=20, verbose_name='First Name')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='Email Address')),
                ('areas', models.ManyToManyField(blank=True, to='avyupskill_app.Area')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
