# Generated by Django 3.1.2 on 2020-11-09 17:16

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(blank=True, max_length=20, null=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=2000)),
                ('location', models.CharField(max_length=100)),
                ('lat', models.FloatField(blank=True, max_length=50)),
                ('lon', models.FloatField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BeaconPark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('lat', models.FloatField(max_length=50)),
                ('lon', models.FloatField(max_length=50)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=100)),
                ('class_type', models.CharField(choices=[('1', 'AIARE 1 '), ('2', 'AIARE 2 '), ('3', 'Avalanche Rescue')], max_length=30)),
                ('location', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('details_url', models.CharField(blank=True, default='', max_length=300)),
                ('aiare_url', models.CharField(blank=True, default='', max_length=300)),
                ('provider_url', models.CharField(blank=True, default='', max_length=300)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('contact_email', models.CharField(blank=True, default='', max_length=100)),
                ('cost', models.CharField(blank=True, default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('1', 'The Worst'), ('2', 'Meh'), ('3', 'Average'), ('4', 'Yay'), ('5', 'The Best')], max_length=1)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='avyupskill_app.area')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to=settings.AUTH_USER_MODEL, verbose_name='The Reviewer')),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_area', to='avyupskill_app.area')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_area', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(max_length=1000)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='avyupskill_app.area')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to=settings.AUTH_USER_MODEL, verbose_name='The Reviewer')),
            ],
        ),
        migrations.CreateModel(
            name='BackcountryDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('journal', models.TextField(max_length=1000)),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backcountry_day', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='fav_areas',
            field=models.ManyToManyField(blank=True, related_name='areas', through='avyupskill_app.FavoriteArea', to='avyupskill_app.Area'),
        ),
    ]
