# Generated by Django 3.1.2 on 2020-11-09 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avyupskill_app', '0002_auto_20201109_1736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fav_areas',
            new_name='areas',
        ),
        migrations.AlterField(
            model_name='favoritearea',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fav_areas', to='avyupskill_app.area'),
        ),
        migrations.AlterField(
            model_name='favoritearea',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fav_areas', to=settings.AUTH_USER_MODEL),
        ),
    ]
