# Generated by Django 3.1.2 on 2020-11-05 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avyupskill_app', '0002_auto_20201105_2007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='areas',
            new_name='saved_areas',
        ),
    ]
