# Generated by Django 3.1.2 on 2020-11-05 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avyupskill_app', '0003_auto_20201105_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='Email Address'),
        ),
    ]
