# Generated by Django 3.1.2 on 2020-11-06 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avyupskill_app', '0006_auto_20201106_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='aiare_url',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='course',
            name='contact_email',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='cost',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='course',
            name='details_url',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='course',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='course',
            name='provider',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='provider_url',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
