import requests
from django.core.management.base import BaseCommand
from ...models import BeaconPark, Area

def seed_parks():
  BeaconPark(description="", name= "Breckenridge Ski Resort", location="Breckenridge, CO", lon="-106.0667", lat="39.4803").save()
  BeaconPark(description="", name= "Keystone Ski Resort", location="Keystone, CO", lon="-105.9437", lat="39.6084").save()
  BeaconPark(description="", name= "Telluride Ski Resort", location="Telluride, CO", lon="-107.812286", lat="37.937492").save()
  BeaconPark(description="", name= "Arapahoe Basin Ski Resort", location="Keystone, CO", lon="-105.8719", lat="39.6425").save()
  BeaconPark(description="", name= "Aspen Highlands", location="Aspen, CO", lon="-106.8554", lat="39.1824").save()
  BeaconPark(description="", name= "Monarch Mountain Ski Resort", location="Salida, CO", lon="-106.3320", lat="38.5121").save()
  BeaconPark(description="", name= "Powderhorn Ski Resort", location="Palisade, CO", lon="-108.15556", lat="39.06306").save()
  BeaconPark(description="", name= "Rocky Mountain National Park - Hidden Valley", location="Estes Park, CO", lon="-105.3392", lat="39.6947").save()
  BeaconPark(description="", name= "Silverton Avalanche School", location="Silverton, CO", lon="-107.6639423", lat="37.8115015").save()
  BeaconPark(description="", name= "Steamboat Ski Resort", location="Steamboat Springs, CO", lon="-106.8045", lat="40.4572").save()
  BeaconPark(description="", name= "Wolf Creek Ski Resort", location="Del Norte, CO", lon="-106.7932", lat="37.4724").save()
  BeaconPark(description="", name= "Aspen Mountain Ski Patrol", location="Aspen", lon="-106.818227", lat="39.1862601").save()
  BeaconPark(description="", name= "Beaver Creek Ski Resort", location="Avon, CO", lon="-106.5167", lat="39.6043").save()
  BeaconPark(description="", name= "Eagle Holy Cross Ranger District", location="Minturn, CO", lon="-106.4365705", lat="39.597727").save()
  BeaconPark(description="", name= "Frisco Adventure Park", location="Frisco, CO", lon="-106.079827", lat="39.5741502").save()
  BeaconPark(description="", name= "Loveland Ski Area", location="Georgetown, CO", lon="-105.8979465", lat="39.6800375").save()
  BeaconPark(description="", name= "Purgatory Ski Resort", location="Durango, CO", lon="-107.8729216", lat="37.6259024").save()
  BeaconPark(description="", name= "Vail Ski Resort", location="Vail, CO", lon="-106.3550", lat="39.6061").save()
  BeaconPark(description="", name= "Winter Park Ski Resort", location="Winter Park, CO", lon="-105.7625", lat="39.8868").save()

def seed_areas():
  Area(name= "Saint Vrain Mountain", description="From the end of the Long Lake Approach, this descent heads down the looker's left side of a wide, exposed bowl. The bowl could be worth exploring but is south/southeast facing with conditions that weren't ideal. The line shown here stays to the looker's left of the bowl with a less-exposed aspect and more terrain features to anchor the snowpack. There are four or five good turns and a small cornice at the top for those looking to send a little airtime. The line trends to the skier's left heading east so as to traverse the bottom of the bowl for a short, side-step of the eastern nose of the bowl to reach another, longer line. This second line has a fun beginning section to a rollover that is worth stopping and scouting. Below the roll-over, there are another three to four turns before you duck into the trees and trend to the left, east, to eventually meet back up with the Long Lake Approach at Long Lake Road. We transitioned at a small lake to make the short skin to reconnect with the Long Lake Approach.", location="Allenspark", lon="-105.5505237", lat="40.159257").save()
  Area(name= "Caribou", description="On a powder day, you'll need a 4WD car to access the top part of Caribou Road since the road is not plowed in the winter. Park alongside the road by the old mining structures, or at the end of the road. The approach is mellow and flat for about 1.75 miles. Take the second fork in the trail, to the right. From the broken down cabins on the left, follow the trail to the right. Here you'll start your ascent up the base of the slope. This hike takes about 10 minutes and there should be a distinct skin track when no fresh snow has fallen. At the top of the knob, head right to the open meadow and choose your line. This area is lap-able without backtracking on the approach. The slope is open and east facing, so prone to wind loading and fills in nice early season, but can lead to stability issues on steeper aspects. Overall, this is a safe and playful slope that you can lap 3 - 4 times on a good day. On the hike out, get ready to strap skins on, as the last section of the hike is a low-grade climb out to the parking lot.", location="Nederland", lon="-105.649182", lat="39.9810673").save()
  Area(name= "Hidden Valley", description="This run is within Rocky Mountain National Park. It is at the old Hidden Valley ski area, which closed in 1991. It is a ski area no more, and is now being returned to the forest. RMNP has a great warming hut and restroom facility at the base, along with ample parking. This area is very popular for the sledding hill not far from the hut. Beyond the sledding hill is where the old ski runs used to be cut through the trees. This run used to be known as Ptarmigan. Back in those days it was a green circle run. Well some things don't change, because it still is. This one is fun to hike up and then glide back down just for a nice little warm up. It's enough to give you a taste and make you really want to climb up the bigger hills for a longer run. It's nice and wide open, sort of like a bunny hill. It can be a little more fun to hike up above this run a bit and start your downhill in the trees...just to spice this one up a bit.", location="Rocky Mountain National Park", lon="-105.6575758", lat="40.3935903").save()
  Area(name= "Floral Park", description="Floral Park is the expansive tree glade zone that skiers and snowboarders easily view when driving north on Highway 40 from Empire. As one approaches Berthoud Pass there are several views and indicators of Floral Park. The first is the queue of hitchhiking riders waiting for a ride at the outlet of the Floral Park runs. Further up the highway and before the Pass there are several views into Floral Park. The runs in Floral Park are easily accessible from the Berthoud Pass summit parking lot. Combine this access with the exit access to Highway 40 it becomes a popular area to ski and then hitchhike back up. The terrain ranges from moderately steep tree skiing to avalanche slopes. This is some of the best tree backcountry skiing on Berthoud Pass. Be careful in this area. Do not let the presence of trees bring your snow safety guard down.", location="Berthoud Pass", lon="-105.7771", lat="39.798").save()
  Area(name= "Dry Gulch", description="Start parallel to I-70 and head down the road grade that eventually tips upwards, climbing into Dry Gulch. This approach isn't hard, per se, but it is fairly long, especially if you factor in the climbing you'll inevitably have to do to get to good skiing.", location="Loveland Pass Exit", lon="-105.8862519", lat="39.6859544").save()
  Area(name= "Jones Pass", description="The skin track follows the Jones Pass Road. The path of the jeep road is obvious, especially after snowmobiles or a snow cat have gone ahead. The road climbs eight tenths of a mile to a clearing below point [39.7793, -105.8638]. At this clearing separate from the Jones Pass Road and head north following a jeep road. This is well defined once Powder Addiction establishes the snow cat road. Continue into the West Fork Bowl, approximately 2.5 miles from the trailhead. Powder Addiction has secured a special use permit from the forest service to provide guided snow cat ski tours of this area. Additionally, Jones Pass has traditionally been used by snowmobiles. This may not be quite the backcountry experience you were hoping for, but it is a huge playground.", location="Empire", lon="-105.9300346", lat="39.7728358").save()
  Area(name= "Saint Mary's Glacier", description="Conditions vary from month to month, and from year to year. If you're expecting amazing turns all year round, this isn't your place. If you just want to get some turns in over the summer, this is it. It can be pretty manky, dirty and difficult in general, but that's half the fun! There is snow here all year round (it got pretty thin, especially that bad year - yeah, you remember that year). There was still snow, but not too much during that bad year. Enough to slide on though.", location="Fall River Road", lon="-105.6416035", lat="39.8095467").save()
  Area(name= "Geneva Basin", description="A long, gradual climb to an old abandoned ski area, Geneva Basin. The Guanella Pass Rd (closed to traffic in winter, but there may be snowmobiles) is paved so it can melt out on low snow years and sunny days. The climb can be long but its usually relatively quiet for the front range. This route takes the road the whole way for extra mileage. The climb tops out at the old ski patrol hut (maintained by volunteers). There are chairs, table, beds and old paraphernalia in the hut. On nice days there is a nice deck to sit outside and take in the view. The hut is a great spot to spend the night or have a snack/lunch. However, the ski patrol shack is said to be haunted! From the hut there are a lot of great skiing options. Be careful going north from the hut toward Square Top Mountain; there are a lot of of slopes that slide and have killed people in the past.", location="Bailey", lon="-105.7251771", lat="39.5660568").save()
  Area(name= "Baldy", description="An easy skin up to the ridge line of Bald Mountain with many good lines that begin off this ascent.", location="Breckenridge", lon="-106.0808336", lat="39.4675902").save()
  Area(name= "Mayflower Gulch", description="This summer road turns into an easy, wide approach to some great terrain. Not only is it easy, it's incredibly scenic to boot.", location="Copper Mountain", lon="-106.2277795", lat="39.4223346").save()
  Area(name= "Gold Hill", description="The approach is up a jeep road at an easy steady grade. When you reach a fork in the trail you'll see old mine buildings. Take the right fork up a steeper skin track that winds to tree line on the hill to your right. Stay below the steeper corniced section at the top for gladed, rolling skiing back to your skin track. When conditions are right continue up the steeper section, above tree line, for access to a short open section leading to the glades mentioned earlier. I like to stay at tree line and ski the glades. The slope is mostly under 25 degrees with some small rollers to keep it fun. This area tends to stay shaded and the snow is generally soft and cold.", location="Breckenridge", lon="-106.15106", lat="39.4223346").save()
  Area(name= "Mount Trelease NE Aspect", description="Use the same approach as with Dry Gulch, then pick an ascent line to your left. Kick a skin track up (many times you can find one already cut) then have some fun skiing down through the trees. There are many options available at various angles.", location="Loveland Pass Exit", lon="-105.8862519", lat="39.6859544").save()
  Area(name= "Humbug to Half Dome", description="Start from the Mayflower Gulch parking area. Just a hundred yards or so up the trail, it opens up with a spectacular view of Fletcher Mountain. From here, find a good place to cross the creek on your left and make your way up to an aqueduct north of the creek. This aqueduct is frequented by snowshoers and other winter travelers, so it's pretty easy to find. Follow this all the way around the west side of Mayflower Hill until you reach the next drainage, which is Humbug Creek. From Humbug Creek Approach, continue up the creek, staying in the belly of the drainage. After passing treeline, bank left while navigating some boulders and work your way into the left drainage that leads to a saddle to the southeast of half dome. Once you reach the saddle, continue up the ridge until you're at your line. The lines down half dome get less steep the further north you hike. Beware of cornices! Due to its aspect, this ridge consistently holds large, dangerous cornices off the N-E side.", location="Copper Mountain", lon="-106.1340579", lat="39.5911661").save()

def clear_seeds():
  BeaconPark.objects.all().delete()
  Area.objects.all().delete()

class Command(BaseCommand):
  def handle(self, *args, **options):
    clear_seeds()
    seed_parks()
    seed_areas()
    print("completed area and beacon park seeds")